/**
 * @file legacyMemoryAudit.ts
 * @description READ-ONLY audit of the pre-3.2A Marketing Memory rows — 3.2A §36.
 *
 *   Categorises what future work each legacy row likely needs. It is
 *   INFORMATIONAL: nothing is reclassified, no scope is invented, no evidence is
 *   fabricated, and no row is modified. ADR-067 C11 requires a founder-visible
 *   audit pass before any legacy row rejoins governed promotion; this produces
 *   the input for that pass, not the pass itself.
 *
 *   Deliberately makes no judgement a human could not check: every category is
 *   derived from a stated, verifiable property of the row.
 *
 * @security Read-only. Performs SELECT only; asserts zero writes by construction.
 * @dependencies supabaseAdmin
 */

import { writeFileSync } from 'fs';
import { join } from 'path';
import { getSupabaseAdmin } from '../src/lib/supabaseAdmin';

type Category =
  | 'SYNTHETIC_BOOTSTRAP'
  | 'DUPLICATE_OF_DOMAIN_STATE'
  | 'UNSUPPORTED_NO_EVIDENCE'
  | 'UNKNOWN_SCOPE'
  | 'POTENTIALLY_LEGITIMATE'
  | 'NEEDS_FOUNDER_REVIEW';

interface Row {
  id: string; title: string; memory_type: string; source: string; status: string;
  confidence: number; content: Record<string, unknown> | null; evidence_ids: string[] | null;
  memory_class: string | null; scope_completeness: string; version: number;
  assertion_class: string | null; product_id: string | null; created_at: string;
}

/** Domain tables that already own the kind of fact a memory_type implies (C2). */
const DOMAIN_OWNED: Record<string, string> = {
  customer:    'products.confirmed_icp / founder_context.audience',
  brand:       'products.brand_voice_profile / product_claims',
  competitor:  'competitor_relationships',
  product:     'products',
  founder:     'founder_context / approval_boundary_policies / business_goals',
};

function categorise(r: Row): { categories: Category[]; notes: string[] } {
  const categories: Category[] = [];
  const notes: string[] = [];

  const content = r.content ?? {};
  if (content.synthetic === true || 'slug' in content || 'note' in content) {
    categories.push('SYNTHETIC_BOOTSTRAP');
    notes.push('content carries seed markers (synthetic/slug/note) rather than a claim');
  }
  if ((r.evidence_ids ?? []).length === 0) {
    categories.push('UNSUPPORTED_NO_EVIDENCE');
    notes.push('no evidence rows are linked, so confidence cannot be recomputed');
  }
  if (r.scope_completeness !== 'explicit' && r.scope_completeness !== 'partial') {
    categories.push('UNKNOWN_SCOPE');
    notes.push('scope is unknown, so the row is quarantined from automated belief change (C11)');
  }
  if (DOMAIN_OWNED[r.memory_type]) {
    categories.push('DUPLICATE_OF_DOMAIN_STATE');
    notes.push(`memory_type '${r.memory_type}' overlaps authoritative state in ${DOMAIN_OWNED[r.memory_type]}`);
  }
  if (typeof content.claim === 'string' && (content.claim as string).length > 20
      && (r.evidence_ids ?? []).length > 0) {
    categories.push('POTENTIALLY_LEGITIMATE');
    notes.push('carries a substantive claim with linked evidence');
  }
  if (r.source === 'founder_feedback' || r.assertion_class === 'founder_assertion') {
    categories.push('NEEDS_FOUNDER_REVIEW');
    notes.push('founder-attributed: only a founder may confirm or retire it');
  }
  if (categories.length === 0) {
    categories.push('NEEDS_FOUNDER_REVIEW');
    notes.push('no automatic category applies; a human must decide');
  }
  return { categories, notes };
}

async function main(): Promise<void> {
  const db = getSupabaseAdmin();
  const { data, error } = await db
    .from('marketing_memories')
    .select('id, title, memory_type, source, status, confidence, content, evidence_ids, ' +
            'memory_class, scope_completeness, version, assertion_class, product_id, created_at')
    .is('memory_class', null)             // legacy discriminator (migration 099)
    .order('created_at', { ascending: true });

  if (error) { console.error('audit failed:', error.message); process.exit(1); }
  const rows = (data ?? []) as Row[];

  console.log(`\nLegacy Marketing Memory audit — ${rows.length} pre-3.2A rows (READ-ONLY)\n`);

  const tally: Record<string, number> = {};
  const lines: string[] = [];
  for (const r of rows) {
    const { categories, notes } = categorise(r);
    for (const c of categories) tally[c] = (tally[c] ?? 0) + 1;
    lines.push(`| ${r.title.slice(0, 46)} | ${r.memory_type} | ${r.source} | ${r.status} | ` +
               `${(r.evidence_ids ?? []).length} | ${r.scope_completeness} | ${categories.join(', ')} |`);
  }

  for (const [k, v] of Object.entries(tally).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${k.padEnd(28)} ${v}`);
  }

  const md = [
    '# Legacy Marketing Memory audit (Phase 3.2A §36)',
    '',
    '> Generated by `backend/scripts/legacyMemoryAudit.ts`. **READ-ONLY and',
    '> INFORMATIONAL.** No row was reclassified, no scope invented, no evidence',
    '> added. ADR-067 C11 requires a founder-visible classification pass before any',
    '> of these rejoin governed promotion; this is the input to that pass.',
    '',
    `Rows audited: **${rows.length}** (every row where \`memory_class IS NULL\`).`,
    '',
    '## Category counts',
    '',
    '| Category | Rows | Meaning |',
    '|---|---|---|',
    `| SYNTHETIC_BOOTSTRAP | ${tally.SYNTHETIC_BOOTSTRAP ?? 0} | content carries seed markers, not a real claim |`,
    `| UNSUPPORTED_NO_EVIDENCE | ${tally.UNSUPPORTED_NO_EVIDENCE ?? 0} | no linked evidence; confidence is unrecomputable |`,
    `| UNKNOWN_SCOPE | ${tally.UNKNOWN_SCOPE ?? 0} | quarantined from automated belief change (C11) |`,
    `| DUPLICATE_OF_DOMAIN_STATE | ${tally.DUPLICATE_OF_DOMAIN_STATE ?? 0} | overlaps a table that already owns this fact (C2) |`,
    `| POTENTIALLY_LEGITIMATE | ${tally.POTENTIALLY_LEGITIMATE ?? 0} | substantive claim WITH evidence |`,
    `| NEEDS_FOUNDER_REVIEW | ${tally.NEEDS_FOUNDER_REVIEW ?? 0} | only a founder can decide |`,
    '',
    'Categories are not exclusive: a row typically carries several.',
    '',
    '## Rows',
    '',
    '| Title | Type | Source | Status | Evidence | Scope | Categories |',
    '|---|---|---|---|---|---|---|',
    ...lines,
    '',
    '## What this implies for Design B',
    '',
    'Every legacy row is quarantined by C11 today: retrievable and usable as',
    'historical context, but never a contradiction target, never superseded, never',
    'reinforced. That is deliberately inert rather than wrong.',
    '',
    'The audit pass itself is Design B work and needs a founder, because deciding',
    'the scope of an existing claim is a judgement about what it was always meant',
    'to mean — not something a model should infer after the fact.',
  ].join('\n');

  const out = join(__dirname, '..', '..', 'docs', 'reviews', 'phase-3.2A-legacy-memory-audit.md');
  writeFileSync(out, md);
  console.log(`\nWrote ${out}\n`);
}

main().catch(e => { console.error('FAILED:', e); process.exit(1); });
