import {it,expect,vi} from 'vitest';
vi.mock('../src/services/marketIntelligence/demandTournamentEvidence',()=>({
 loadDurableDemandTournament:vi.fn(async()=>null),
 persistDurableDemandTournament:vi.fn(async()=>{}),
}));
import {demandWindow,planDemandTournament,executeDemandTournament,validDemandTournament,loadDemandTournament,type TournamentRequest} from '../src/services/marketIntelligence/demandTournament';
import {normalizeDemand,serviceDemandQueryDetails,searchDemandReadiness,type DemandRequest} from '../src/services/marketIntelligence/searchDemandAdapter';
import {normalizeServiceArea} from '../src/services/content/serviceGeography';
import {rankGroundedOpportunities} from '../src/services/opportunity/groundedOpportunity';
const now=new Date(),area=normalizeServiceArea({city:'Phoenix',state:'Arizona',country:'US'});
const entries=Array.from({length:7},(_,i)=>({id:String(i),name:`Service ${i}`,status:'CONFIRMED',kind:'SERVICE',source:'OWNER_CONFIRMED',serviceArea:area,fulfillmentGeographies:[area.displayLabel]}));
const request:TournamentRequest={workspaceId:'w',productId:'p',geography:'US-AZ',window:demandWindow(now),services:entries.map(e=>({id:e.id,query:serviceDemandQueryDetails(e.name).query,normalizationReason:serviceDemandQueryDetails(e.name).reason,ownerGeography:area}))};
function response(r:DemandRequest,stage:number){const scores=stage===1?{'0':10,'1':20,'2':90,'3':30,'4':40}:{'2':10,'5':15,'6':20};
 const raw={search_parameters:{geo:r.geography,date:`${r.window!.start} ${r.window!.end}`,data_type:'TIMESERIES'},interest_over_time:{timeline_data:Array.from({length:13},(_,i)=>({timestamp:String((Date.parse(r.window!.start)+Math.floor(i*89/12)*86400000)/1000),values:r.services.map(s=>({query:s.query,extracted_value:scores[s.id as keyof typeof scores]??10}))}))}};
 return {signals:normalizeDemand(raw,r,now.toISOString()),unavailable:null};}
const run=()=>executeDemandTournament(request,async r=>response(r,r.services.length===5?1:2),now);
function context(result:any){return {workspaceId:'w',productId:'p',application:{name:'Business',description:'Confirmed services',markets:[]},founderDirection:{primaryGoal:'Customer engagement',audienceConfirmed:'Local customers'},evidence:[],offerings:entries.map(e=>({id:e.id,name:e.name,source:'OWNER_CONFIRMED'})),signalFoundation:{catalog:{confirmed:entries,discovered:[],requiresCatalog:true},demand:[],demandTournament:result,ownedSignals:[],connections:[]}} as any;}
it('groups by stable identity independently of input order or demand',()=>{expect(planDemandTournament({...request,services:[...request.services].reverse()}).first.map(s=>s.id)).toEqual(['0','1','2','3','4']);expect(planDemandTournament(request).remaining.map(s=>s.id)).toEqual(['5','6']);expect(searchDemandReadiness(entries,true,'ACTIVE').ready).toBe(true);});
it('advances the first winner and selects only by the final comparison, not cross-stage indices',async()=>{const calls:DemandRequest[]=[];const result=await executeDemandTournament(request,async r=>{calls.push(r);return response(r,calls.length);},now);expect(calls).toHaveLength(2);expect(calls[1].services.map(s=>s.id)).toEqual(['2','5','6']);expect(result.stages[0].winnerId).toBe('2');expect(result.finalWinnerId).toBe('6');expect(result.stages[0].signals.find(s=>s.serviceId==='4')!.value).toBe(40);expect(result.stages[1].signals.find(s=>s.serviceId==='6')!.value).toBe(20);expect(validDemandTournament(result,request,now)).toBe(true);});
it('uses one fixed 90-day geography/window and retains query, group and advancement lineage',async()=>{const r=await run();expect(Date.parse(request.window.end)-Date.parse(request.window.start)).toBe(89*86400000);expect(r.stages.every(s=>s.geography==='US-AZ'&&JSON.stringify(s.window)===JSON.stringify(request.window))).toBe(true);expect(r.stages[0].comparisonGroupId).not.toBe(r.stages[1].comparisonGroupId);expect(r.provenanceId).toHaveLength(64);expect(r.stages[1].signals[0].normalizationReason).toContain('v2');expect(r.stages[1].signals[0].ownerGeography?.city).toBe('Phoenix');expect(r.stages[1].serviceIds).toContain(r.stages[0].winnerId);});
it('does not promote Stage 1 if Stage 2 fails or throws',async()=>{for(const throws of [false,true]){let calls=0;const r=await executeDemandTournament(request,async req=>{if(++calls===1)return response(req,1);if(throws)throw Error('transport');return {signals:[],unavailable:'failure'};},now);expect(r.status).toBe('FAILED');expect(r.finalWinnerId).toBeNull();expect(r.stages).toHaveLength(1);const ranked=rankGroundedOpportunities(context(r));expect(ranked.selected).toBeNull();expect(ranked.alternatives.every(c=>!c.concepts.length)).toBe(true);}});
it('stops after an incomplete first comparison',async()=>{let calls=0;const r=await executeDemandTournament(request,async req=>{calls++;const res=response(req,1);res.signals.pop();return res;},now);expect(calls).toBe(1);expect(r.finalWinnerId).toBeNull();});
it('fails closed for zero, sparse, tied and near-tied observations',async()=>{for(const kind of ['zero','sparse','tie','near']){let calls=0;const r=await executeDemandTournament(request,async req=>{calls++;const res=response(req,1);res.signals.forEach(s=>{s.samples=s.samples!.map((p,i)=>({...p,value:kind==='zero'?0:kind==='sparse'?(i===0?30:0):kind==='near'?(s.serviceId==='2'?50:49):50}));s.value=s.samples.reduce((a,p)=>a+p.value,0)/s.samples.length;});return res;},now);expect(r.finalWinnerId).toBeNull();expect(calls).toBe(1);}});
it('rejects wrong geography, stale observations, malformed samples and mismatched windows',async()=>{for(const kind of ['geo','stale','window','malformed','fixture']){const r=await executeDemandTournament(request,async req=>{const res=response(req,1);const s=res.signals[0];if(kind==='geo')s.geography='US-CA';if(kind==='stale')s.freshness='STALE';if(kind==='window')s.requestedWindow={start:'2000-01-01',end:'2000-01-02'};if(kind==='malformed')s.samples![0].value=NaN;if(kind==='fixture')s.fixture=true;return res;},now);expect(r.finalWinnerId).toBeNull();}});
it('rejects a changed observed time grid in the final stage',async()=>{let calls=0;const r=await executeDemandTournament(request,async req=>{const res=response(req,++calls);if(calls===2)for(const s of res.signals){s.samples!.splice(1,1);s.value=s.samples!.reduce((sum,p)=>sum+p.value,0)/s.samples!.length;}return res;},now);expect(r.status).toBe('FAILED');expect(r.finalWinnerId).toBeNull();});
it('rechecks workspace, services, queries, freshness and stage lineage before ranking',async()=>{const result=await run();expect(validDemandTournament(result,{...request,workspaceId:'other'},now)).toBe(false);const bad=structuredClone(result);bad.stages[1].winnerId='5';expect(validDemandTournament(bad,request,now)).toBe(false);expect(validDemandTournament(result,request,new Date(now.getTime()+90*86400000))).toBe(false);const ctx=context(result);ctx.signalFoundation.catalog.confirmed=[...entries,{...entries[0],id:'new'}];expect(rankGroundedOpportunities(ctx).selected).toBeNull();});
it('existing ranking selects the valid final demand candidate with LIMITED grounded A/B/C',async()=>{const result=await run(),ranked=rankGroundedOpportunities(context(result));expect(ranked.selected?.serviceId).toBe('6');expect(ranked.selected?.confidence).toBe('LIMITED');expect(ranked.selected?.whyNow[0]).toContain('final comparison');expect(ranked.selected?.concepts.map(c=>c.key)).toEqual(['A','B','C']);expect(ranked.selected?.concepts.every(c=>c.serviceId==='6'&&c.opportunityId===ranked.selected?.id)).toBe(true);expect(ranked.selected?.brief.demandEvidence?.stage).toBe(2);expect(ranked.selected?.dimensions.find(d=>d.name==='Conversion/performance')?.points).toBeNull();expect(ranked.selected?.brief.marketMoment[0].ref).toBe(result.stages[1].signals.find(s=>s.serviceId==='6')?.provenanceId);});
it('does not alter owner-priority weight to force the demand winner',async()=>{const ctx=context(await run());ctx.founderDirection.contextDelta='Service 0 customers are not reachable after they submit a request';const ranked=rankGroundedOpportunities(ctx);expect(ranked.selected?.serviceId).toBe('0');expect(ranked.selected?.dimensions.find(d=>d.name==='Strategic priority')?.points).toBe(2);});
it('uses transparent generic consumer queries',()=>{expect(serviceDemandQueryDetails('Electrical')).toEqual({query:'electrician',reason:expect.stringContaining('electrical')});expect(serviceDemandQueryDetails('Plumbing').query).toBe('plumber');expect(serviceDemandQueryDetails('HVAC & AC Repair').query).toBe('air conditioning repair');expect(serviceDemandQueryDetails('Makeup Artist').query).toBe('makeup artist');expect(serviceDemandQueryDetails('Roof Repair').query).toBe('roof repair');});
it('makes zero provider calls and no recommendation without credentials',async()=>{vi.stubEnv('SERPAPI_API_KEY','');vi.stubEnv('MARKET_INTELLIGENCE_MODE','ACTIVE');const fetch=vi.fn();vi.stubGlobal('fetch',fetch);try{const r=await loadDemandTournament(request);expect(r.status).toBe('UNAVAILABLE');expect(fetch).not.toHaveBeenCalled();expect(rankGroundedOpportunities(context(r)).selected).toBeNull();}finally{vi.unstubAllEnvs();vi.unstubAllGlobals();}});
it('coalesces concurrent read-model loads into at most two provider requests and reuses the result',async()=>{vi.stubEnv('SERPAPI_API_KEY','test-only');vi.stubEnv('MARKET_INTELLIGENCE_MODE','ACTIVE');let calls=0;const cachedRequest={...request,workspaceId:'cache-test'};vi.stubGlobal('fetch',vi.fn(async(url:URL)=>{const q=url.searchParams.get('q')!.split(',');const req={...cachedRequest,services:cachedRequest.services.filter(s=>q.includes(s.query)).sort((a,b)=>q.indexOf(a.query)-q.indexOf(b.query))};const result=response(req,++calls);return {ok:true,json:async()=>({search_parameters:{geo:'US-AZ',date:`${request.window.start} ${request.window.end}`,data_type:'TIMESERIES'},interest_over_time:{timeline_data:result.signals[0].samples!.map((p,i)=>({timestamp:String(Date.parse(p.timestamp)/1000),values:result.signals.map(s=>({query:s.query,extracted_value:s.samples![i].value}))}))}})};}));try{const [a,b]=await Promise.all([loadDemandTournament(cachedRequest),loadDemandTournament(cachedRequest)]);expect(a.status).toBe('COMPLETE');expect(b.finalWinnerId).toBe('6');expect(calls).toBe(2);await loadDemandTournament(cachedRequest);expect(calls).toBe(2);}finally{vi.unstubAllEnvs();vi.unstubAllGlobals();}});

it('accepts complete zero and sparse losing candidates without dropping their observations',async()=>{
 const result=await executeDemandTournament(request,async req=>{const res=response(req,req.services.length===5?1:2);for(const s of res.signals.filter(s=>['0','1'].includes(s.serviceId))){s.samples=s.samples!.map((p,i)=>({...p,value:s.serviceId==='0'?0:i===0?1:0}));s.value=s.samples.reduce((a,p)=>a+p.value,0)/s.samples.length;}return res;},now);
 expect(result.status).toBe('COMPLETE');expect(result.finalWinnerId).toBe('6');expect(result.stages[0].signals).toHaveLength(5);expect(result.stages[0].signals[0].samples).toHaveLength(13);expect(result.stages[0].signals[0].value).toBe(0);expect(validDemandTournament(result,request,now)).toBe(true);
});
it('rejects missing, duplicate, wrong-query and nonnumeric observations even for a low candidate',async()=>{for(const kind of ['missing','duplicate','query','numeric']){const result=await executeDemandTournament(request,async req=>{const res=response(req,1),s=res.signals[0];if(kind==='missing')s.samples!.splice(1,1);if(kind==='duplicate')s.samples![1].timestamp=s.samples![0].timestamp;if(kind==='query')s.query='wrong';if(kind==='numeric')s.samples![0].value=NaN;return res;},now);expect(result.status).toBe('FAILED');expect(result.finalWinnerId).toBeNull();}});
it('rejects a dominant but insufficiently sustained winner',async()=>{const result=await executeDemandTournament(request,async req=>{const res=response(req,1);for(const s of res.signals){s.samples=s.samples!.map((p,i)=>({...p,value:s.serviceId==='2'&&i<5?100:0}));s.value=s.samples.reduce((a,p)=>a+p.value,0)/s.samples.length;}return res;},now);expect(result.finalWinnerId).toBeNull();});
