import {it,expect,vi} from 'vitest';
const m=vi.hoisted(()=>({row:{structured_data:{kind:'GROUNDED_PLANNING_WORK'},updated_at:'2026-09-20T19:45:47.873+00:00'} as any}));
vi.mock('../src/lib/supabaseAdmin',()=>({getSupabaseAdmin:()=>({from:()=>{let update:any,filters:any[]=[];const q:any={select:()=>q,eq:(k:string,v:any)=>{filters.push([k,v]);return q},is:()=>q,update:(v:any)=>{update=v;return q},single:async()=>({data:structuredClone(m.row),error:null})};q.then=(ok:any)=>{const match=filters.every(([k,v])=>k==='updated_at'?new Date(m.row.updated_at).getTime()===new Date(v).getTime():k==='structured_data->generation->>attemptId'?m.row.structured_data.generation.attemptId===v:true);if(update&&match)Object.assign(m.row,update);return Promise.resolve({data:match?[{id:'p'}]:[],error:null}).then(ok)};return q}})}));
import {beginPlanningRun,finishPlanningRun,productionOutcome,productionState,recoverPlanningRun} from '../src/services/content/planningProductionState';
it('persists creating then failure so a fresh read cannot hide it, and rejects overlapping clicks',async()=>{const run=await beginPlanningRun('p','w');expect(productionState(m.row.structured_data)).toBe('CREATING');await expect(beginPlanningRun('p','w')).rejects.toThrow('already in progress');await finishPlanningRun('p','w',run.attemptId,{disposition:'REWRITE_REQUIRED',quality:{factualSafety:'NOT_SUPPORTED'}},200);expect(productionState(structuredClone(m.row.structured_data))).toBe('NEEDS_ATTENTION');expect(m.row.structured_data.generation.reason).toBe('UNSUPPORTED_WORDING');});
it('only points to review when an eligible artifact was actually persisted',()=>{expect(productionOutcome({ownerState:'READY_FOR_OWNER_REVIEW'},200).status).toBe('NEEDS_ATTENTION');expect(productionOutcome({ownerState:'READY_FOR_OWNER_REVIEW',assetId:'actual',versionNumber:1},201)).toEqual({status:'READY_FOR_REVIEW',assetId:'actual',versionNumber:1,reason:'NONE'});});
it('recovers a retained owner-reviewable candidate without a new generation action',async()=>{const run=await beginPlanningRun('p','w');await finishPlanningRun('p','w',run.attemptId,{disposition:'REWRITE_REQUIRED',quality:{factualSafety:'CERTIFIED_SUPPORTED'}},200);const recovered=await recoverPlanningRun('p','w',run.attemptId,{ownerState:'READY_FOR_OWNER_REVIEW',assetId:'actual',versionNumber:1});expect(recovered.status).toBe('READY_FOR_REVIEW');expect(recovered.attemptId).toBe(run.attemptId);expect(recovered.recoveredBy).toBe('GOVERNED_REEVALUATION');});
it('retains known downstream failures instead of collapsing them into UNKNOWN',()=>{
 expect(productionOutcome({disposition:'REWRITE_REQUIRED'},200)).toMatchObject({status:'NEEDS_ATTENTION',reason:'CONTENT_REFINEMENT_REQUIRED'});
 expect(productionOutcome({failureClass:'ARTIFACT_PERSISTENCE_FAILED'},500)).toMatchObject({status:'NEEDS_ATTENTION',reason:'ARTIFACT_PERSISTENCE_FAILED'});
 expect(productionOutcome({failureClass:'ORCHESTRATION_FAILED'},500)).toMatchObject({status:'NEEDS_ATTENTION',reason:'ORCHESTRATION_FAILED'});
});
