import {normalizeServiceArea} from '../src/services/content/serviceGeography';
import {it,expect,vi} from 'vitest';
import {searchDemandReadiness,serviceDemandQuery,fetchSearchDemand} from '../src/services/marketIntelligence/searchDemandAdapter';
const services=(count:number,area='US-AZ')=>Array.from({length:count},(_,i)=>({id:String(i),name:`Service ${i}`,fulfillmentGeographies:[area],serviceArea:area==='US-AZ'?normalizeServiceArea({city:'Phoenix',state:'Arizona',country:'US'}):null}));
it('allows seven services through the bounded two-stage comparison when prerequisites are valid',()=>{const r=searchDemandReadiness(services(7),true,'ACTIVE');expect(r.ready).toBe(true);expect(r.comparisonSupported).toBe(true);expect(r.eligibleCount).toBe(7);});
it('does not infer a provider area from narrative Phoenix context or unknown areas',()=>{expect(searchDemandReadiness(services(7,'so focusing on Phoenix now'),false,'SHADOW').geography).toBeNull();expect(searchDemandReadiness([{id:'x',name:'Service',fulfillmentGeographies:[]}],true,'ACTIVE').ready).toBe(false);});
it('requires the complete set to share a safe normalized geography',()=>{expect(searchDemandReadiness(services(2,'United States'),true,'ACTIVE').geography).toBeNull();const set=services(2);set[1].serviceArea=normalizeServiceArea({city:'',state:'California',country:'US'});expect(searchDemandReadiness(set,true,'ACTIVE').ready).toBe(false);expect(searchDemandReadiness(services(2),false,'ACTIVE').ready).toBe(false);expect(searchDemandReadiness(services(2),true,'SHADOW').ready).toBe(false);});
it('makes transparent bounded service queries without replacing meaning',()=>{expect(serviceDemandQuery(' HVAC & AC Repair ')).toBe('air conditioning repair');expect(serviceDemandQuery('Electrical')).toBe('electrician');expect(serviceDemandQuery('House Cleaning')).toBe('house cleaning service');});
it('never calls the provider without configured access',async()=>{vi.stubEnv('MARKET_INTELLIGENCE_MODE','ACTIVE');vi.stubEnv('SERPAPI_API_KEY','');const fetch=vi.fn();vi.stubGlobal('fetch',fetch);try{expect((await fetchSearchDemand({workspaceId:'w',productId:'p',geography:'US-AZ',services:[{id:'x',query:'service'}]})).signals).toEqual([]);expect(fetch).not.toHaveBeenCalled();}finally{vi.unstubAllEnvs();vi.unstubAllGlobals();}});
