-- Migration 071: Add direction_meta JSONB column to strategy_directions
-- Stores extended direction fields generated by Claude (biggest_constraint,
-- first_mission, immediate_action, success_signal, confidence_level, primary_objective).
-- These are separate from week_1-4 and key_assumptions to keep the schema clean.
-- All existing rows get direction_meta = NULL (handled gracefully by frontend fallbacks).

ALTER TABLE strategy_directions
  ADD COLUMN IF NOT EXISTS direction_meta JSONB;
