/**
 * @migration 20260720_000063_discovery_jobs
 * @description Durable discovery job record for Phase 1.
 *   Tracks BullMQ job state, 11-stage progress, structured output from scrapers,
 *   and the preliminary growth report generated by Claude.
 * @security RLS: founders access only their own jobs.
 */

CREATE TABLE IF NOT EXISTS discovery_jobs (
  id                   UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id           UUID        NOT NULL REFERENCES onboarding_sessions(id) ON DELETE CASCADE,
  founder_id           UUID        NOT NULL REFERENCES founders(id) ON DELETE CASCADE,

  -- BullMQ job reference
  queue_job_id         TEXT,

  -- Status
  status               TEXT        NOT NULL DEFAULT 'queued'
                       CHECK (status IN ('queued','running','completed','failed','cancelled')),

  -- Progress (0–100)
  progress             INTEGER     NOT NULL DEFAULT 0,
  progress_stage       INTEGER     NOT NULL DEFAULT 0, -- 1–11
  progress_message     TEXT,

  -- Input
  urls_submitted       TEXT[]      NOT NULL DEFAULT ARRAY[]::TEXT[],
  private_description  TEXT,

  -- Detected platform
  detected_platform    TEXT        CHECK (detected_platform IN ('app_store','play_store','web_only','unknown')),
  store_url            TEXT,       -- canonical app store URL
  website_url          TEXT,

  -- Multiple match scenario
  candidate_matches    JSONB,      -- array of {id, name, url, icon, rating, reviews} when >1 found
  selected_match_id    TEXT,       -- which match the founder picked

  -- Structured output (populated on success)
  app_metadata         JSONB,      -- scraped app data
  icp_data             JSONB,      -- structured ICP from Claude
  competitor_data      JSONB,      -- found competitors
  website_meta         JSONB,      -- scraped website data

  -- Preliminary growth report (generated by Claude)
  report_data          JSONB,      -- { headline, summary, topInsights[], opportunities[], risks[] }
  report_acknowledged  BOOLEAN     NOT NULL DEFAULT false,

  -- Error handling
  error_code           TEXT,       -- e.g. APP_NOT_FOUND, STORE_PARSE_FAILED, etc.
  error_message        TEXT,
  retry_count          INTEGER     NOT NULL DEFAULT 0,
  max_retries          INTEGER     NOT NULL DEFAULT 3,
  last_attempted_at    TIMESTAMPTZ,

  -- AI usage
  ai_tokens_consumed   INTEGER     NOT NULL DEFAULT 0,

  created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE discovery_jobs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "discovery_jobs_owner"
  ON discovery_jobs
  USING (founder_id = auth.uid());

CREATE INDEX IF NOT EXISTS discovery_jobs_session
  ON discovery_jobs (session_id);
CREATE INDEX IF NOT EXISTS discovery_jobs_founder_status
  ON discovery_jobs (founder_id, status);
