/**
 * @file claimCandidateBuilder.ts
 * @description Converts normalised structured evidence into a candidate claim —
 *   Phase 3.1G §3.
 *
 *   THE BOUNDARY THIS ENFORCES: no raw provider text is ever promoted into a
 *   belief. A candidate is built from STRUCTURED fields — channel, metric,
 *   value, comparison, timeframe — through a deterministic template. Provider
 *   prose is attached as evidence, never as the claim, because a claim becomes
 *   something LaunchMind asserts and provider text is something a third party
 *   wrote.
 *
 *   DETERMINISTIC TEMPLATES ONLY, for now. Every builder here is a pure function
 *   of already-normalised numbers. No model is consulted to WRITE a claim: a
 *   generated sentence that overstates what the numbers support would enter the
 *   corpus as a first-class belief with no way to tell it apart from a measured
 *   one. Model assistance belongs to comparison, where it is advisory.
 *
 *   INGESTION IS FLAG-GUARDED (§21). `CONTINUOUS_LEARNING_INGESTION_MODE`:
 *     off     nothing is built or ingested
 *     shadow  candidates are built, compared and decided — and the decision is
 *             RECORDED, not applied. The default.
 *     active  decisions are applied through MemoryLifecycleService.
 *
 *   Shadow is the default deliberately: automatic learning that mutates memory
 *   should be observed on real signals before it is trusted to change what
 *   LaunchMind believes.
 *
 * @security Builds claims only from structured numeric/enumerated fields.
 *   Free-text provider content cannot reach the claim body.
 * @dependencies connection_insights, claimComparison, beliefPolicy
 */

import * as Sentry from '@sentry/node';
import { getSupabaseAdmin } from '../../lib/supabaseAdmin';
import { newTraceId } from '../../lib/traceId';
import type { ComparableClaim } from './claimComparison';
import { compareClaims } from './claimComparison';
import { decide, type ClaimClassification } from './beliefPolicy';

export type IngestionMode = 'off' | 'shadow' | 'active';

/**
 * Resolves the rollout mode.
 *
 * An empty env var is not nullish, so `??` alone would yield '' — the trap this
 * codebase has hit three times. Unknown values resolve to `shadow`, never to
 * `active`: an operator typo must not silently enable automatic learning.
 */
export function ingestionMode(): IngestionMode {
  const raw = (process.env.CONTINUOUS_LEARNING_INGESTION_MODE ?? '').trim().toLowerCase();
  if (raw === 'off' || raw === 'shadow' || raw === 'active') return raw;
  return 'shadow';
}

export interface ClaimCandidate {
  claim: ComparableClaim;
  /** Which precedence tier this evidence carries. */
  source: string;
  workspaceId: string;
  productId: string | null;
  evidenceIds: string[];
  /** Canonical provenance of the underlying observation. */
  provenance: { kind: string; sourceId: string; provider?: string | null };
}

// ── Builders (deterministic templates) ───────────────────────────────────────

interface InsightRow {
  id: string; workspace_id: string; product_id: string | null;
  // `insight_key` is the real column (migration 084) — a stable rule identifier
  // such as 'app_store.conversion_below_benchmark'. An earlier version of this
  // file selected a non-existent `insight_type`, which made PostgREST error and
  // silently yield zero candidates on every run.
  provider: string; insight_key: string; headline: string; detail: string;
  evidence: Array<{ label: string; value: string }> | null;
  source_signal_ids: string[] | null; provenance: Record<string, unknown> | null;
  confidence: number; created_at: string;
}

/**
 * Builds a candidate from a connection insight.
 *
 * A connection insight is already a derived finding with evidence and
 * provenance (Step 3 of Improve Intelligence), which makes it the one existing
 * source that can form a defensible claim without inventing anything.
 *
 * The claim text is the insight's HEADLINE — LaunchMind-authored, generated by
 * a deterministic rule from real numbers. The `detail` prose and any provider
 * strings stay in evidence.
 *
 * @returns A candidate, or null when the insight lacks what a claim needs.
 */
export function buildFromConnectionInsight(row: InsightRow): ClaimCandidate | null {
  if (!row.headline || row.headline.trim().length < 8) return null;
  if (!row.workspace_id) return null;

  // Scope is read from structured evidence labels, never parsed out of prose.
  const byLabel = new Map((row.evidence ?? []).map(e => [e.label.toLowerCase(), e.value]));
  const scope: ComparableClaim['scope'] = {
    channel:   byLabel.get('channel')   ?? providerChannel(row.provider),
    segment:   byLabel.get('segment')   ?? null,
    market:    byLabel.get('market')    ?? null,
    timeframe: byLabel.get('period')    ?? byLabel.get('timeframe') ?? null,
    productId: row.product_id,
  };

  return {
    claim: { text: row.headline.trim(), scope, memoryType: memoryTypeFor(row.insight_key) },
    // A provider observation is first-party outcome data, not a founder statement.
    source: 'analytics',
    workspaceId: row.workspace_id,
    productId: row.product_id,
    evidenceIds: [],   // connection insights are not `evidence` rows; provenance below
    provenance: { kind: 'connection_insight', sourceId: row.id, provider: row.provider },
  };
}

function providerChannel(provider: string): string | null {
  return {
    google_ads: 'google_ads', meta: 'meta', search_console: 'organic',
    mailchimp: 'email', ga4: null, app_store_connect: 'app_store',
    revenue_cat: null, stripe: null, hubspot: null,
  }[provider] ?? null;
}

/** Maps a rule identifier such as `meta.creative_fatigue` to a memory type. */
function memoryTypeFor(insightKey: string): string {
  if (/creative|fatigue/i.test(insightKey)) return 'creative';
  if (/conversion|campaign|spend|cac/i.test(insightKey)) return 'campaign';
  if (/audience|segment|retention|subscriber|lifecycle/i.test(insightKey)) return 'customer';
  if (/territory|market/i.test(insightKey)) return 'market';
  return 'campaign';
}

/**
 * Builds a candidate from a campaign outcome.
 *
 * The claim is assembled from NUMBERS the platform reported — channel, market,
 * CTR — through a fixed template. Nothing here is written by a model, and no
 * free text from the payload reaches the claim body.
 *
 * @returns A candidate, or null when the payload lacks the channel the claim is
 *   about, or lacks any metric to assert. A claim with no measurement behind it
 *   is a sentence, not a belief.
 */
export function buildFromCampaignResult(
  workspaceId: string,
  productId: string | null,
  payload: Record<string, unknown>,
): ClaimCandidate | null {
  const channel = typeof payload.channel === 'string' ? payload.channel : null;
  if (!channel) return null;

  const market = typeof payload.market === 'string' ? payload.market : null;
  const ctr    = typeof payload.ctr === 'number' ? payload.ctr : null;
  const cpi    = typeof payload.cpi === 'number' ? payload.cpi : null;
  const installs = typeof payload.installs === 'number' ? payload.installs : null;
  if (ctr === null && cpi === null && installs === null) return null;

  // Bands, not adjectives invented per call: the same numbers must always
  // produce the same sentence, or two identical outcomes become two beliefs.
  const band = ctr === null ? null : ctr > 0.04 ? 'strongly' : ctr > 0.02 ? 'moderately' : 'weakly';
  const scopeText = market ? ` in ${market}` : '';
  const text = band
    ? `${channel}${scopeText} performed ${band} on click-through (${(ctr! * 100).toFixed(2)}%).`
    : `${channel}${scopeText} produced ${installs ?? 0} installs at a cost per install of ${cpi ?? 'unknown'}.`;

  return {
    claim: {
      text,
      scope: { channel, market, segment: null, timeframe: null, productId },
      memoryType: 'campaign',
    },
    source: 'campaign_performance',
    workspaceId, productId, evidenceIds: [],
    provenance: {
      kind: 'campaign_result',
      sourceId: typeof payload.campaignId === 'string' ? payload.campaignId : 'unknown',
      provider: channel,
    },
  };
}

/**
 * Builds a candidate from an experiment outcome.
 *
 * An experiment is the highest-quality evidence LaunchMind can hold, because it
 * was designed to answer one question. It is still routed through comparison:
 * a significant result that contradicts a founder statement must be surfaced for
 * review, not applied because the statistics were good.
 *
 * @returns A candidate, or null when the experiment is inconclusive. An
 *   inconclusive experiment genuinely teaches nothing and must not become a
 *   belief with a confidence attached to it.
 */
export function buildFromExperimentResult(
  workspaceId: string,
  productId: string | null,
  payload: Record<string, unknown>,
): ClaimCandidate | null {
  const hypothesis = typeof payload.hypothesis === 'string' ? payload.hypothesis.trim() : '';
  const outcome    = typeof payload.outcome === 'string' ? payload.outcome.trim() : '';
  if (hypothesis.length < 8 || !outcome) return null;
  if (payload.significant === false) return null;

  return {
    claim: {
      text: `Experiment result: ${hypothesis} — ${outcome}`,
      scope: {
        channel:   typeof payload.channel === 'string' ? payload.channel : null,
        segment:   typeof payload.segment === 'string' ? payload.segment : null,
        market:    typeof payload.market === 'string' ? payload.market : null,
        timeframe: null,
        productId,
      },
      memoryType: 'experiment',
    },
    source: 'experiment',
    workspaceId, productId, evidenceIds: [],
    provenance: {
      kind: 'experiment_result',
      sourceId: typeof payload.experimentId === 'string' ? payload.experimentId : 'unknown',
      provider: null,
    },
  };
}

// ── The single Class-A ingestion door (§10) ──────────────────────────────────

export interface ClassAIngestOutcome {
  mode: IngestionMode;
  built: boolean;
  applied: boolean;
  decision: ShadowDecision | null;
  reason: string;
}

/**
 * The ONE path by which an automated observation may reach Marketing Memory.
 *
 * Before this existed, `campaign_result` and `experiment_result` called
 * `upsertMemory()` directly: a title-equality duplicate check, a flat +0.05
 * confidence bump on every re-ingest, and no comparison of what the new claim
 * actually SAID relative to the old one. Two contradictory campaign outcomes
 * with the same generated title reinforced each other.
 *
 * Routing them here means every automated claim is compared and policed by the
 * same rules as any other, and — critically — that an automated source still
 * cannot override a founder statement, because `decide()` is the only thing
 * that says what may happen.
 *
 * @param candidate Built by one of the deterministic builders above.
 * @param opts.apply Injected by the caller so this module still imports no
 *   mutation service (ADR-066 invariant 3, enforced structurally by test).
 * @returns What was decided and whether it was applied. In `shadow` — the
 *   default — `applied` is always false.
 */
export async function ingestClassACandidate(
  candidate: ClaimCandidate | null,
  existing: Array<{ id: string; title: string; content: Record<string, unknown> | null;
                    source: string; memory_type: string; product_id: string | null }>,
  opts: {
    allowModel?: boolean;
    apply?: (decision: ShadowDecision, candidate: ClaimCandidate) => Promise<void>;
  } = {},
): Promise<ClassAIngestOutcome> {
  const mode = ingestionMode();
  if (mode === 'off') {
    return { mode, built: false, applied: false, decision: null, reason: 'ingestion disabled' };
  }
  if (!candidate) {
    return { mode, built: false, applied: false, decision: null,
             reason: 'payload did not support a defensible claim' };
  }

  const decision = await decideForCandidate(candidate, existing, opts.allowModel === true);

  if (mode !== 'active') {
    // SHADOW: everything real happened except the write. This is the state the
    // system ships in.
    return { mode, built: true, applied: false, decision, reason: 'shadow mode records, never applies' };
  }
  if (!opts.apply) {
    return { mode, built: true, applied: false, decision, reason: 'no applier supplied' };
  }
  if (decision.requiresFounderReview) {
    return { mode, built: true, applied: false, decision,
             reason: 'decision requires founder review; queued rather than applied' };
  }

  await opts.apply(decision, candidate);
  return { mode, built: true, applied: true, decision, reason: 'applied' };
}

/** Compares a candidate against existing beliefs and returns the policy decision. */
async function decideForCandidate(
  cand: ClaimCandidate,
  existing: Array<{ id: string; title: string; content: Record<string, unknown> | null;
                    source: string; memory_type: string; product_id: string | null }>,
  allowModel: boolean,
): Promise<ShadowDecision> {
  for (const m of existing) {
    const mClaim: ComparableClaim = {
      text: typeof m.content?.claim === 'string' ? m.content.claim : m.title,
      scope: {
        channel:   (m.content?.channel as string) ?? null,
        segment:   (m.content?.segment as string) ?? null,
        market:    (m.content?.market as string) ?? null,
        timeframe: (m.content?.timeframe as string) ?? null,
        productId: m.product_id,
      },
      memoryType: m.memory_type,
    };
    const cmp = await compareClaims(mClaim, cand.claim, { allowModel });
    if (cmp.classification === 'UNRELATED') continue;

    const d = decide(cmp.classification, m.source, cand.source);
    return {
      candidateText: cand.claim.text,
      matchedMemoryId: m.id, matchedMemoryTitle: m.title,
      classification: cmp.classification,
      proposedAction: d.action, requiresFounderReview: d.requiresFounderReview,
      decidedBy: cmp.decidedBy, rationaleCode: cmp.rationaleCode,
      reason: d.reason, provenance: cand.provenance,
    };
  }

  return {
    candidateText: cand.claim.text, matchedMemoryId: null, matchedMemoryTitle: null,
    classification: 'NO_MATCH', proposedAction: 'create_new', requiresFounderReview: false,
    decidedBy: 'deterministic', rationaleCode: 'NO_RELATED_MEMORY',
    reason: 'no existing belief relates to this observation', provenance: cand.provenance,
  };
}

// ── Shadow evaluation ────────────────────────────────────────────────────────

export interface ShadowDecision {
  candidateText: string;
  matchedMemoryId: string | null;
  matchedMemoryTitle: string | null;
  classification: ClaimClassification | 'NO_MATCH';
  proposedAction: 'reinforce' | 'challenge' | 'supersede' | 'none' | 'create_new';
  requiresFounderReview: boolean;
  decidedBy: string;
  rationaleCode: string;
  reason: string;
  provenance: ClaimCandidate['provenance'];
}

export interface ShadowReport {
  mode: IngestionMode;
  workspaceId: string;
  candidatesBuilt: number;
  decisions: ShadowDecision[];
  counts: Record<string, number>;
  traceId: string;
}

/**
 * Runs the full loop WITHOUT mutating memory.
 *
 * Everything real happens — candidate construction, related-memory retrieval,
 * comparison, policy — and the decision is returned instead of applied. This is
 * what makes it safe to point at production signals before automatic learning
 * is trusted.
 *
 * @param opts.limit Maximum insights to evaluate in one pass.
 */
export async function runShadowIngestion(
  workspaceId: string,
  opts: { limit?: number; allowModel?: boolean; traceId?: string } = {},
): Promise<ShadowReport> {
  const traceId = opts.traceId ?? newTraceId();
  const db = getSupabaseAdmin();
  const mode = ingestionMode();
  const decisions: ShadowDecision[] = [];

  if (mode === 'off') {
    return { mode, workspaceId, candidatesBuilt: 0, decisions: [], counts: {}, traceId };
  }

  const { data: insights, error: insightError } = await db.from('connection_insights')
    .select('id, workspace_id, product_id, provider, insight_key, headline, detail, evidence, source_signal_ids, provenance, confidence, created_at')
    .eq('workspace_id', workspaceId)
    .order('created_at', { ascending: false })
    .limit(opts.limit ?? 50);

  // Surfaced, not swallowed. Reading zero insights because the query FAILED is a
  // different fact from reading zero because there are none, and conflating them
  // is what let a broken column name look like "nothing to learn from".
  if (insightError) {
    Sentry.captureMessage('shadow ingestion could not read connection insights', {
      level: 'error', tags: { workspaceId }, extra: { code: insightError.code },
    });
    throw new Error(`connection_insights unreadable: ${insightError.message}`);
  }

  const candidates = ((insights ?? []) as InsightRow[])
    .map(buildFromConnectionInsight)
    .filter((c): c is ClaimCandidate => c !== null);

  // Existing beliefs to compare against. Active only — a candidate should not be
  // matched against something LaunchMind has already retracted.
  const { data: memories } = await db.from('marketing_memories')
    .select('id, title, content, source, memory_type, product_id, status')
    .eq('workspace_id', workspaceId).eq('status', 'active');

  const existing = ((memories ?? []) as Array<{
    id: string; title: string; content: Record<string, unknown> | null;
    source: string; memory_type: string; product_id: string | null;
  }>);

  for (const cand of candidates) {
    let best: { id: string; title: string; source: string; result: Awaited<ReturnType<typeof compareClaims>> } | null = null;

    for (const m of existing) {
      const mClaim: ComparableClaim = {
        text: typeof m.content?.claim === 'string' ? m.content.claim : m.title,
        scope: {
          channel:   (m.content?.channel as string) ?? null,
          segment:   (m.content?.segment as string) ?? null,
          market:    (m.content?.market as string) ?? null,
          timeframe: (m.content?.timeframe as string) ?? null,
          productId: m.product_id,
        },
        memoryType: m.memory_type,
      };
      const result = await compareClaims(mClaim, cand.claim, { allowModel: opts.allowModel === true });
      // Anything other than UNRELATED is a match worth reporting; the first
      // decisive one wins, which keeps a shadow pass bounded.
      if (result.classification !== 'UNRELATED') {
        best = { id: m.id, title: m.title, source: m.source, result };
        break;
      }
    }

    if (!best) {
      decisions.push({
        candidateText: cand.claim.text, matchedMemoryId: null, matchedMemoryTitle: null,
        classification: 'NO_MATCH',
        // A genuinely new observation is a CREATION decision, which belongs to
        // the ingestion pipeline, not to comparison (§11 of 3.1F).
        proposedAction: 'create_new', requiresFounderReview: false,
        decidedBy: 'deterministic', rationaleCode: 'NO_RELATED_MEMORY',
        reason: 'no existing belief relates to this observation',
        provenance: cand.provenance,
      });
      continue;
    }

    const d = decide(best.result.classification, best.source, cand.source);
    decisions.push({
      candidateText: cand.claim.text,
      matchedMemoryId: best.id, matchedMemoryTitle: best.title,
      classification: best.result.classification,
      proposedAction: d.action, requiresFounderReview: d.requiresFounderReview,
      decidedBy: best.result.decidedBy, rationaleCode: best.result.rationaleCode,
      reason: d.reason, provenance: cand.provenance,
    });
  }

  const counts: Record<string, number> = {};
  for (const d of decisions) {
    counts[d.classification] = (counts[d.classification] ?? 0) + 1;
    counts[`action:${d.proposedAction}`] = (counts[`action:${d.proposedAction}`] ?? 0) + 1;
    if (d.requiresFounderReview) counts['founder_review'] = (counts['founder_review'] ?? 0) + 1;
  }

  if (mode === 'active') {
    // Guard rail, not an apology: ACTIVE is deliberately not reachable from this
    // function. Applying a decision goes through MemoryLifecycleService, which
    // is the only writer, and enabling it is an explicit operational step.
    Sentry.captureMessage('continuous learning ACTIVE mode requested but shadow report was run', {
      level: 'warning', tags: { workspaceId },
    });
  }

  return { mode, workspaceId, candidatesBuilt: candidates.length, decisions, counts, traceId };
}
