/**
 * @file app/(dashboard)/dashboard/briefs/page.tsx
 * @description Weekly briefs list — Sunday performance briefs generated by the AI engine.
 *   Two-column layout: brief list on left, generated assets + next 7 days on right.
 * @security Auth token from Supabase session. All data via Fastify backend.
 * @dependencies lib/api, lib/supabase/client
 */

'use client';

import { useEffect, useState, useCallback } from 'react';
import { createClient } from '@/lib/supabase/client';
import { api, ApiError } from '@/lib/api';
import type { WeeklyBrief } from '@/lib/api';
import { trackOnboarding } from '@/lib/analytics';

const STATUS_STYLE: Record<WeeklyBrief['status'], React.CSSProperties> = {
  draft: { background: 'var(--raised)', color: 'var(--ink2)', border: '1px solid var(--border2)' },
  sent: { background: 'var(--indigo-d)', color: 'var(--indigo)', border: '1px solid var(--indigo-b)' },
  acknowledged: { background: 'var(--sage-d)', color: 'var(--sage)', border: '1px solid var(--sage-b)' },
};

const STATUS_LABEL: Record<WeeklyBrief['status'], string> = {
  draft: 'Draft',
  sent: 'Sent',
  acknowledged: 'Acknowledged',
};

interface GeneratedAsset {
  channel: string;
  type: string;
  copy?: string;
  headline?: string;
  approved?: boolean;
}

export default function BriefsPage() {
  const supabase = createClient();
  const [briefs, setBriefs] = useState<WeeklyBrief[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return;
      const { briefs: data } = await api.briefs.list(session.access_token);
      setBriefs(data);
      if (data.length > 0) setSelectedId(data[0].id);
      if (data.some(b => b.status === 'sent' || b.status === 'acknowledged')) {
        trackOnboarding('brief_received', { count: data.length });
      }
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Failed to load briefs');
    } finally {
      setLoading(false);
    }
  }, [supabase]);

  useEffect(() => { load(); }, [load]);

  const selectedBrief = briefs.find((b) => b.id === selectedId) ?? null;

  return (
    <div className="p-8" style={{ maxWidth: 1100 }}>
      <div className="mb-6">
        <h1 className="font-display font-semibold" style={{ fontSize: 22, color: 'var(--ink)' }}>
          Weekly brief
        </h1>
        <p style={{ fontSize: 13, color: 'var(--ink2)', marginTop: 4 }}>
          Sunday performance briefs generated from your campaign data.
        </p>
      </div>

      {error && (
        <div className="mb-4 rounded-[8px] px-4 py-3" style={{ background: 'var(--red-d)', border: '1px solid var(--red-b)', color: 'var(--red)', fontSize: 13 }}>
          {error}
        </div>
      )}

      {loading ? (
        <div className="text-center py-16" style={{ fontSize: 13, color: 'var(--ink3)' }}>Loading briefs…</div>
      ) : briefs.length === 0 ? (
        <EmptyState />
      ) : (
        <div className="grid gap-5" style={{ gridTemplateColumns: '340px 1fr' }}>
          {/* Left column — brief list */}
          <div className="space-y-2">
            {briefs.map((brief) => (
              <button
                key={brief.id}
                onClick={() => setSelectedId(brief.id)}
                className="w-full rounded-[10px] px-4 py-3 text-left transition-all"
                style={{
                  background: selectedId === brief.id ? 'var(--surface)' : 'transparent',
                  border: selectedId === brief.id ? '1.5px solid var(--sage-b)' : '1px solid var(--border)',
                  cursor: 'pointer',
                }}
              >
                <div className="flex items-center justify-between mb-1">
                  <span className="font-semibold" style={{ fontSize: 13, color: 'var(--ink)' }}>
                    {brief.productName ?? 'Unknown product'}
                  </span>
                  <span className="rounded-full px-2 py-0.5 font-medium" style={{ fontSize: 10, ...STATUS_STYLE[brief.status] }}>
                    {STATUS_LABEL[brief.status]}
                  </span>
                </div>
                <div className="flex items-center gap-2" style={{ fontSize: 12, color: 'var(--ink3)' }}>
                  <span>Week of {new Date(brief.week_of).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
                </div>
                {brief.what_worked && (
                  <p className="mt-1 truncate" style={{ fontSize: 12, color: 'var(--ink2)' }}>
                    ✅ {brief.what_worked}
                  </p>
                )}
              </button>
            ))}
          </div>

          {/* Right column — brief detail + assets */}
          {selectedBrief && (
            <BriefDetail brief={selectedBrief} />
          )}
        </div>
      )}
    </div>
  );
}

function BriefDetail({ brief }: { brief: WeeklyBrief }) {
  const nextActions = brief.next_actions as { actions?: string[] } | null;
  const generatedAssets = brief.generated_assets as { assets?: GeneratedAsset[] } | null;
  const assets = generatedAssets?.assets ?? [];
  const [approvedAssets, setApprovedAssets] = useState<Set<number>>(new Set());

  function toggleApprove(i: number) {
    setApprovedAssets((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i); else next.add(i);
      return next;
    });
  }

  return (
    <div className="space-y-4">
      {/* What worked / What to kill */}
      <div className="grid grid-cols-2 gap-4">
        {brief.what_worked && (
          <div
            className="rounded-[10px] p-5"
            style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
          >
            <p className="font-semibold mb-2" style={{ fontSize: 11, color: 'var(--sage)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              ● What worked
            </p>
            <p style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.6 }}>{brief.what_worked}</p>
          </div>
        )}
        {brief.what_to_kill && (
          <div
            className="rounded-[10px] p-5"
            style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
          >
            <p className="font-semibold mb-2" style={{ fontSize: 11, color: 'var(--red)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
              ● What to kill
            </p>
            <p style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.6 }}>{brief.what_to_kill}</p>
          </div>
        )}
      </div>

      {/* Next 7 days */}
      {nextActions?.actions && nextActions.actions.length > 0 && (
        <div
          className="rounded-[10px] p-5"
          style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
        >
          <p className="font-semibold mb-3" style={{ fontSize: 11, color: 'var(--ink2)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            Next 7 days
          </p>
          <ul className="space-y-2">
            {nextActions.actions.map((action: string, i: number) => (
              <li key={i} className="flex items-start gap-2.5">
                <span
                  className="flex-shrink-0 mt-0.5 rounded-full w-5 h-5 flex items-center justify-center font-semibold"
                  style={{ background: 'var(--sage-d)', color: 'var(--sage)', fontSize: 10 }}
                >
                  {i + 1}
                </span>
                <span style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.5 }}>{action}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Generated assets */}
      {assets.length > 0 && (
        <div
          className="rounded-[10px] p-5"
          style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
        >
          <p className="font-semibold mb-3" style={{ fontSize: 11, color: 'var(--ink2)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
            Generated assets
          </p>
          <div className="space-y-3">
            {assets.map((asset, i) => (
              <div
                key={i}
                className="rounded-[8px] p-4"
                style={{
                  background: 'var(--raised)',
                  border: approvedAssets.has(i) ? '1.5px solid var(--sage-b)' : '1px solid var(--border)',
                }}
              >
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    <span
                      className="rounded-full px-2 py-0.5 font-medium"
                      style={{ fontSize: 11, background: 'var(--indigo-d)', color: 'var(--indigo)', border: '1px solid var(--indigo-b)' }}
                    >
                      {asset.channel}
                    </span>
                    <span style={{ fontSize: 11, color: 'var(--ink3)' }}>{asset.type}</span>
                  </div>
                  <button
                    onClick={() => toggleApprove(i)}
                    className="rounded-[6px] px-3 py-1 font-medium transition-all"
                    style={{
                      fontSize: 11,
                      background: approvedAssets.has(i) ? 'var(--sage)' : 'var(--sage-d)',
                      border: `1px solid var(--sage-b)`,
                      color: approvedAssets.has(i) ? '#fff' : 'var(--sage)',
                      cursor: 'pointer',
                    }}
                  >
                    {approvedAssets.has(i) ? '✓ Approved' : 'Approve'}
                  </button>
                </div>
                {asset.headline && (
                  <p className="font-medium mb-1" style={{ fontSize: 13, color: 'var(--ink)' }}>{asset.headline}</p>
                )}
                {asset.copy && (
                  <p style={{ fontSize: 12, color: 'var(--ink2)', lineHeight: 1.5 }}>{asset.copy}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {brief.sent_at && (
        <p style={{ fontSize: 11, color: 'var(--ink3)' }}>
          Sent {new Date(brief.sent_at).toLocaleDateString()}
        </p>
      )}
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-24 text-center">
      <div
        className="w-14 h-14 rounded-full flex items-center justify-center mb-4"
        style={{ background: 'var(--raised)' }}
      >
        <svg style={{ width: 24, height: 24, color: 'var(--ink3)' }} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      </div>
      <h3 className="font-semibold mb-2" style={{ fontSize: 15, color: 'var(--ink)' }}>
        No weekly briefs yet
      </h3>
      <p style={{ fontSize: 13, color: 'var(--ink2)', maxWidth: 340 }}>
        Briefs are generated every Sunday once your campaigns have at least one week of data. Check back after your first campaign runs.
      </p>
    </div>
  );
}
