/**
 * @file app/(dashboard)/dashboard/briefs/page.tsx
 * @description Weekly briefs list — Sunday performance briefs generated by the AI engine.
 *   Shows week_of, product, status, and expandable what_worked/what_to_kill/next_actions.
 * @security Auth token from Supabase session. All data via Fastify backend.
 * @dependencies lib/api, lib/supabase/client
 */

'use client';

import { useEffect, useState, useCallback } from 'react';
import { createClient } from '@/lib/supabase/client';
import { api, ApiError } from '@/lib/api';
import type { WeeklyBrief } from '@/lib/api';

const STATUS_STYLE: Record<WeeklyBrief['status'], React.CSSProperties> = {
  draft: { background: 'var(--raised)', color: 'var(--ink2)', border: '1px solid var(--border2)' },
  sent: { background: 'var(--indigo-d)', color: 'var(--indigo)', border: '1px solid var(--indigo-b)' },
  acknowledged: { background: 'var(--sage-d)', color: 'var(--sage)', border: '1px solid var(--sage-b)' },
};

const STATUS_LABEL: Record<WeeklyBrief['status'], string> = {
  draft: 'Draft',
  sent: 'Sent',
  acknowledged: 'Acknowledged',
};

export default function BriefsPage() {
  const supabase = createClient();
  const [briefs, setBriefs] = useState<WeeklyBrief[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) return;
      const { briefs: data } = await api.briefs.list(session.access_token);
      setBriefs(data);
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Failed to load briefs');
    } finally {
      setLoading(false);
    }
  }, [supabase]);

  useEffect(() => { load(); }, [load]);

  return (
    <div className="p-8 max-w-3xl">
      <div className="mb-6">
        <h1 className="font-display font-semibold" style={{ fontSize: 22, color: 'var(--ink)' }}>
          Weekly Briefs
        </h1>
        <p style={{ fontSize: 13, color: 'var(--ink2)', marginTop: 4 }}>
          Sunday performance briefs generated from your campaign data.
        </p>
      </div>

      {error && (
        <div className="mb-4 rounded-[8px] px-4 py-3" style={{ background: 'var(--red-d)', border: '1px solid var(--red-b)', color: 'var(--red)', fontSize: 13 }}>
          {error}
        </div>
      )}

      {loading ? (
        <div className="text-center py-16" style={{ fontSize: 13, color: 'var(--ink3)' }}>Loading briefs…</div>
      ) : briefs.length === 0 ? (
        <EmptyState />
      ) : (
        <div className="space-y-3">
          {briefs.map((brief) => (
            <BriefCard
              key={brief.id}
              brief={brief}
              isExpanded={expanded === brief.id}
              onToggle={() => setExpanded(expanded === brief.id ? null : brief.id)}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function BriefCard({
  brief,
  isExpanded,
  onToggle,
}: {
  brief: WeeklyBrief;
  isExpanded: boolean;
  onToggle: () => void;
}) {
  const nextActions = brief.next_actions as { actions?: string[] } | null;

  return (
    <div
      className="rounded-[10px] overflow-hidden"
      style={{ background: 'var(--surface)', border: '1px solid var(--border)' }}
    >
      <button
        onClick={onToggle}
        className="w-full flex items-center justify-between px-5 py-4 text-left transition-colors"
        onMouseEnter={e => !isExpanded && ((e.currentTarget as HTMLElement).style.background = 'var(--raised)')}
        onMouseLeave={e => !isExpanded && ((e.currentTarget as HTMLElement).style.background = 'transparent')}
      >
        <div className="flex items-center gap-3 flex-1 min-w-0">
          <div className="flex-shrink-0 text-center">
            <div className="font-mono font-semibold" style={{ fontSize: 13, color: 'var(--ink)' }}>
              {new Date(brief.week_of).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
            </div>
            <div style={{ fontSize: 11, color: 'var(--ink3)' }}>
              {new Date(brief.week_of).getFullYear()}
            </div>
          </div>
          <div className="min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="font-medium truncate" style={{ fontSize: 13, color: 'var(--ink)' }}>
                {brief.productName ?? 'Unknown product'}
              </span>
              <span className="rounded-full px-2 py-0.5 font-medium flex-shrink-0" style={{ fontSize: 11, ...STATUS_STYLE[brief.status] }}>
                {STATUS_LABEL[brief.status]}
              </span>
            </div>
            {brief.what_worked && (
              <p className="truncate mt-0.5" style={{ fontSize: 12, color: 'var(--ink3)', maxWidth: 400 }}>
                {brief.what_worked}
              </p>
            )}
          </div>
        </div>
        <span className="ml-3 flex-shrink-0" style={{ color: 'var(--ink3)', fontSize: 13 }}>
          {isExpanded ? '▲' : '▼'}
        </span>
      </button>

      {isExpanded && (
        <div className="px-5 pb-5 space-y-4" style={{ borderTop: '1px solid var(--border)' }}>
          {brief.what_worked && (
            <Section label="What worked" color="var(--sage)">
              {brief.what_worked}
            </Section>
          )}
          {brief.what_to_kill && (
            <Section label="What to kill" color="var(--red)">
              {brief.what_to_kill}
            </Section>
          )}
          {nextActions?.actions && nextActions.actions.length > 0 && (
            <div className="pt-1">
              <p className="mb-2 font-medium" style={{ fontSize: 11, color: 'var(--ink2)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
                Next actions
              </p>
              <ul className="space-y-2">
                {nextActions.actions.map((action: string, i: number) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="flex-shrink-0 mt-0.5 rounded-full w-4 h-4 flex items-center justify-center" style={{ background: 'var(--sage-d)', color: 'var(--sage)', fontSize: 9, fontWeight: 700 }}>
                      {i + 1}
                    </span>
                    <span style={{ fontSize: 13, color: 'var(--ink)' }}>{action}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}
          {brief.sent_at && (
            <p style={{ fontSize: 11, color: 'var(--ink3)' }}>
              Sent {new Date(brief.sent_at).toLocaleDateString()}
            </p>
          )}
        </div>
      )}
    </div>
  );
}

function Section({ label, color, children }: { label: string; color: string; children: string }) {
  return (
    <div className="pt-4">
      <p className="mb-1.5 font-medium" style={{ fontSize: 11, color: 'var(--ink2)', textTransform: 'uppercase', letterSpacing: '0.04em' }}>
        <span style={{ color, marginRight: 4 }}>●</span>
        {label}
      </p>
      <p style={{ fontSize: 13, color: 'var(--ink)', lineHeight: 1.6 }}>{children}</p>
    </div>
  );
}

function EmptyState() {
  return (
    <div className="flex flex-col items-center justify-center py-24 text-center">
      <div
        className="w-14 h-14 rounded-full flex items-center justify-center mb-4"
        style={{ background: 'var(--raised)' }}
      >
        <svg style={{ width: 24, height: 24, color: 'var(--ink3)' }} fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
        </svg>
      </div>
      <h3 className="font-semibold mb-2" style={{ fontSize: 15, color: 'var(--ink)' }}>
        No weekly briefs yet
      </h3>
      <p style={{ fontSize: 13, color: 'var(--ink2)', maxWidth: 340 }}>
        Briefs are generated every Sunday once your campaigns have at least one week of data. Check back after your first campaign runs.
      </p>
    </div>
  );
}
